AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      
      ImageId: ami-02e136e904f3da870
      
      InstanceType: t2.micro
      
      KeyName: firstkey
      
      SecurityGroups:
        - aa.role.sec.group
      
      Tags:
        - Key: Name
          Value: WebServerofProject-01

      UserData: 
        !Base64 |
        #! /bin/bash
        #update os
        sudo yum update -y
        #install git
        sudo yum install git -y
        #install apache server
        sudo yum install -y httpd
        systemctl start httpd
        systemctl enable httpd
        git clone https://github.com/alpbayramoglu/my-projects.git 
        sudo cp /my-projects/projects/aws/Project-101-kittens-carousel-static-website-ec2/static-web/* /var/www/html
               



      

      
     
